export {
  PaymentIcon,
  AnalyticsIcon,
  ChatIcon,
  FacebookIcon,
  HeartIcon,
  HeartIconTemplateOne,
  HelpIcon,
  LikeIcon,
  MobileMenu,
  NavAdsIcon,
  NavChartIcon,
  NavDeliveryIcon,
  NavHomeIcon,
  NavMenuIcon,
  NavProductIcon,
  NavProfileIcon,
  NavSearch,
  NavSupportIcon,
  NavTagIcon,
  NotifyIcon,
  RateIcon,
  RatingsIcon,
  ReviewRatingsIcon,
  RewardIcon,
  ShoppingCartIcon,
  StarIcon,
  WalletIcon,
  HeartIconStorefront2,
  BusinessThemesIcon,
  NavAffiliatesIcon,
  ContentsCreationIcon,
  // ContentsCreationIcon,
} from './svgs';
